{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "request new/retry",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(upbit_quotation_request_new_total[1m])",
     "legendFormat": "new"
    },
    {
     "expr": "increase(upbit_quotation_request_retry_total[1m])",
     "legendFormat": "retry"
    }
   ]
  },
  {
   "title": "request duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(upbit_quotation_request_success_duration_milliseconds_sum[1m]))/sum(rate(upbit_quotation_request_success_duration_milliseconds_count[1m]))  ",
     "legendFormat": "success request duration"
    },
    {
     "expr": "sum(rate(upbit_quotation_request_failed_duration_milliseconds_sum[1m]))/sum(rate(upbit_quotation_request_failed_duration_milliseconds_count[1m]))",
     "legendFormat": "failed request duration"
    }
   ]
  },
  {
   "title": "request success/failed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(upbit_quotation_response_success_total[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "increase(upbit_quotation_response_failed_total[1m])",
     "legendFormat": "failed"
    }
   ]
  }
 ]
}